---
baseurl: "http://example.org/"
languageCode: en
title: My New Hugo Site
# theme
theme: "hugo-now"
# Comment the themesDir option if you use this theme in production
themesDir: ../..

taxonomies:
  category: "categories"
  tag: "tags"

params:
  description: Hugo port of Jekyll Now
  author: Hugo Now
  keywords: ["hugo-now", "hugo"]
  avatar: /images/hugo.png
  displayauthor: false
  # pygments
  PygmentsUseClasses: true
  PygmentsCodeFences: true
  # pagination
  paginate: 10
  paginatePath: page
  # google analytics
  # GoogleAnalytics: UA-XXXXXX